name: formio_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^3.0.4
  webview_flutter_plus: ^0.3.0+2

  # formio_flutter:
  #   git:
  #     url: https://github.com/emtec-de/formio_flutter
  #     ref: master

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/form.html
    - assets/form.json
    - assets/script.js
